ServerPrefix: '&7[&3&lAEC&7]&r'

#Messages
NoPermission: '&cNo permission.'
ValueChanged: '&c%enchant% &elevel of &6%player% &ehas been set to &d%amount%'
MaxValue: '&cMax level for &6%enchant% &cis &d%level%'
NoPlayer: '&6%player% &cis not online.'
NotEnabled: '&6%enchant% &cis disabled.'

#Enchants
#You can enable or disable enchants from here or in-game
fortune: 'true'
protection: 'true'
thorns: 'true'
featherfalling: 'true'
knockback: 'true'
looting: 'true'